#define IDENTIFIER 1
#define NUMBER 2
#define OPERATION 3
#define RELATIONAL_OPERATION 4
#define TYPE 5
#define IF 6
#define ELSE 7
#define WHILE 8
#define FOR 9
#define SEMICOLON 10
#define LEFT_PARANTHES 11
#define RIGHT_PARANTHES 12
#define LEFT_BRACE 13
#define RIGHT_BRACE 14